package com.axis.model;

import java.util.HashSet;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

@DynamoDBTable(tableName = "user")
public class User {
	
	@DynamoDBRangeKey
	@DynamoDBAutoGeneratedKey
	private String userId;
	@DynamoDBAttribute
	private String name;
	@DynamoDBHashKey(attributeName = "username")
	private String username;
	@DynamoDBIndexRangeKey(attributeName="email", 
            localSecondaryIndexName="username-email-index")
	private String email;
	@DynamoDBAttribute
	@JsonProperty(access = Access.WRITE_ONLY)
	private String password;
	@DynamoDBAttribute
	@JsonProperty(access = Access.WRITE_ONLY)
	private String salt;
	@DynamoDBAttribute
	private String role;

	public User() {
	}

	public User(String name, String username, String email, String password, String salt) {
		this.name = name;
		this.username = username;
		this.email = email;
		this.password = password;
		this.salt = salt;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String id) {
		this.userId = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	public String getSalt() {
		return salt;
	}
	
	public void setSalt(String salt) {
		this.salt = salt;
	}
}