package com.axis.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "order")
public class Order {
	@DynamoDBRangeKey
	@DynamoDBAutoGeneratedKey
	private String orderId;
	@DynamoDBHashKey
	private String userId;
	@DynamoDBAttribute
	private String custAddrId;
	@DynamoDBAttribute
	private String recepientName;

	@DynamoDBAttribute
	private String recepientPhoneNumber;

	@DynamoDBAttribute
	private String pinCode;
	@DynamoDBAttribute
	private String address;
	@DynamoDBAttribute
	private Date orderDate;
	@DynamoDBAttribute
	private int totalAmount;
	@DynamoDBAttribute
	private String status;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private List<OrderItem> orderItem;

	public Order() {
		super();
	}

	public Order(String orderId) {
		super();
		this.orderId = orderId;
	}

	public Order(String orderId, String userId, String custAddrId, String recepientName, String pinCode, String address,
			Date orderDate, int totalAmount, String status, List<OrderItem> orderItem) {
		super();
		this.orderId = orderId;
		this.userId = userId;
		this.custAddrId = custAddrId;
		this.recepientName = recepientName;
		this.pinCode = pinCode;
		this.address = address;
		this.orderDate = orderDate;
		this.totalAmount = totalAmount;
		this.status = status;
		this.orderItem = orderItem;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCustAddrId() {
		return custAddrId;
	}

	public void setCustAddrId(String custAddrId) {
		this.custAddrId = custAddrId;
	}

	public String getRecepientName() {
		return recepientName;
	}

	public void setRecepientName(String recepientName) {
		this.recepientName = recepientName;
	}

	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getOrderDate() {
		return orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public int getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(int totalAmount) {
		this.totalAmount = totalAmount;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<OrderItem> getOrderItem() {
		return orderItem;
	}

	public void setOrderItem(List<OrderItem> orderItem) {
		this.orderItem = orderItem;
	}

	public String getRecepientPhoneNumber() {
		return recepientPhoneNumber;
	}

	public void setRecepientPhoneNumber(String recepientPhoneNumber) {
		this.recepientPhoneNumber = recepientPhoneNumber;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Order [orderId=" + orderId + ", userId=" + userId + ", custAddrId=" + custAddrId + ", recepientName="
				+ recepientName + ", pinCode=" + pinCode + ", address=" + address + ", orderDate=" + orderDate
				+ ", totalAmount=" + totalAmount + ", status=" + status + ", orderItem=" + orderItem + "]";
	}

}
