package com.axis.model;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "product")
public class Product {

	@DynamoDBHashKey(attributeName = "productId")
	@DynamoDBAutoGeneratedKey
	private String productId;
	@DynamoDBAttribute
	private String productName;
	@DynamoDBAttribute
	private String productSummary;
	@DynamoDBAttribute
	private String productDesc;
	@DynamoDBAttribute
	private int views;
	@DynamoDBAttribute
	private int sellingPrice;
	@DynamoDBAttribute
	private int costPrice;
	@DynamoDBAttribute
	private int quantities;
	@DynamoDBAttribute
	private Set<String> imageUrls1;

	@DynamoDBAttribute
	private String mainCategoryId;
	@DynamoDBAttribute
	private String subCategoryId;

	@DynamoDBAttribute
	private String mainCategoryName;
	@DynamoDBAttribute
	private String subCategoryName;

	public Product() {
		super();
	}

	public Product(String productId, String productName, String productSummary, String productDesc, int views,
			int sellingPrice, int costPrice, int quantities, Set<String> imageUrls1, String mainCategoryId,
			String subCategoryId, String mainCategoryName, String subCategoryName) {
		super();
		this.productId = productId;
		this.productName = productName;
		this.productSummary = productSummary;
		this.productDesc = productDesc;
		this.views = views;
		this.sellingPrice = sellingPrice;
		this.costPrice = costPrice;
		this.quantities = quantities;
		this.imageUrls1 = imageUrls1;
		this.mainCategoryId = mainCategoryId;
		this.subCategoryId = subCategoryId;
		this.subCategoryName = subCategoryName;
		this.mainCategoryName = mainCategoryName;
	}
	public Product(String productId, int quantities) {
		super();
		this.productId = productId;
		this.quantities = quantities;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductSummary() {
		return productSummary;
	}

	public void setProductSummary(String productSummary) {
		this.productSummary = productSummary;
	}

	public String getProductDesc() {
		return productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public int getViews() {
		return views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public int getSellingPrice() {
		return sellingPrice;
	}

	public void setSellingPrice(int sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	public int getCostPrice() {
		return costPrice;
	}

	public void setCostPrice(int costPrice) {
		this.costPrice = costPrice;
	}

	public int getQuantities() {
		return quantities;
	}

	public void setQuantities(int quantities) {
		this.quantities = quantities;
	}

	public Set<String> getImageUrls1() {
		return imageUrls1;
	}

	public void setImageUrls1(Set<String> imageUrls1) {
		this.imageUrls1 = imageUrls1;
	}

	public String getMainCategoryId() {
		return mainCategoryId;
	}

	public void setMainCategoryId(String mainCategoryId) {
		this.mainCategoryId = mainCategoryId;
	}

	public String getSubCategoryId() {
		return subCategoryId;
	}

	public void setSubCategoryId(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public String getMainCategoryName() {
		return mainCategoryName;
	}

	public void setMainCategoryName(String mainCategoryName) {
		this.mainCategoryName = mainCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	public String getSubCategoryName() {
		return subCategoryName;
	}

	@Override
	public String toString() {
		return "Product [productId=" + productId + ", productName=" + productName + ", productSummary=" + productSummary
				+ ", productDesc=" + productDesc + ", views=" + views + ", sellingPrice=" + sellingPrice
				+ ", costPrice=" + costPrice + ", quantities=" + quantities + ", imageUrls1=" + imageUrls1 + "]";
	}

}
